name: flutter_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8
  cached_network_image: ^3.3.1 # For efficient image loading from URLs
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/maggi_goreng.jpg
    - assets/nasi_goreng.jpeg
    - assets/sandwich_telur.jpg
    - assets/chef.jpg
    - assets/selangor.jpg
    - assets/pahang.png
    - assets/johor.jpg
    - assets/perak.jpg
